config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :pages, :only => [:index, :show]
  root to: "pages#index"
  resources :users, :only => [:show, :update] do
    resources :workouts
  end
  resources :users, :only => [] do
    resources :meals
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/exercise.rb
class Exercise < ActiveRecord::Base
  validates :cal_min, :description, :presence => true
  has_many :workouts
  has_many :users, through: :workouts
end

app/models/food.rb
class Food < ActiveRecord::Base
  validates :name, :cal_serving, :presence => true
  has_many :meals
  has_many :users, through: :meals
end

app/models/meal.rb
class Meal < ActiveRecord::Base
  belongs_to :user
  belongs_to :food
  validates :user_id, :food_id, :servings, :cal_gained, :presence => true

  def meal_calc
    current_food_cal = Food.find(self.food_id).cal_serving
    current_servings = self.servings
    current_food_cal * current_servings
  end

  def self.total_cal_gained(user_id)
    user = User.find(user_id)
    meals = user.meals
    totalMeal = 0
    meals.each do |meal|
      totalMeal += meal.cal_gained
    end
    return totalMeal
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :workouts
  has_many :exercises, through: :workouts

  has_many :meals
  has_many :foods, through: :meals

end

app/models/workout.rb
class Workout < ActiveRecord::Base
  validates :user_id, :exercise_id, :minutes, :cal_burned, :presence => true
  belongs_to :user
  belongs_to :exercise

  def workout_calc
    current_exercise_cal = Exercise.find(self.exercise_id).cal_min
    current_minutes = self.minutes
    current_exercise_cal * current_minutes
  end

  def self.total_cal_burned(user_id)
    user = User.find(user_id)
    workouts = user.workouts
    totalWorkout = 0
    workouts.each do |workout|
      totalWorkout += workout.cal_burned
    end
    totalWorkout
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/meals_controller.rb
class MealsController < ApplicationController
  def index
    @user = current_user
    @meals = @user.meals
  end

  def new
    @user = current_user
    @meal = Meal.new
    @foods = Food.all
  end

  def create
    @user = current_user
    @meal = @user.meals.new(meal_params)
    @meal.cal_gained = @meal.meal_calc
    if @meal.save
      @user.cal_rem = @user.cal_rem - @meal.cal_gained
      @user.save
      @total_cal_gained = Meal.total_cal_gained(@user.id)
      flash[:notice] = "Meal successfully added!"
      respond_to do |format|
        format.html { redirect_to root_path }
        format.js { render layout: false }
      end
    else
      render :new
    end
  end


private
  def meal_params
    params.require(:meal).permit(:user_id, :food_id, :servings)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, :only => [:index]

  def index
    if params[:search]
      @food_results = params[:search]==""? Food.all : Food.fuzzy_search(params[:search]).order(:name).paginate(:page => params[:page])
      respond_to do |format|
        format.html { redirect_to root_path }
        format.js { render layout: false }
      end
    else
      @food_results = Food.all
    end
    @meal = Meal.new
    @foods = Food.all
    @workout = Workout.new
    @exercises = Exercise.all

    if current_user
      @user = current_user
      @total_cal_gained = Meal.total_cal_gained(@user.id)
      @total_cal_burned = Workout.total_cal_burned(@user.id)
    end
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
  end

  def update
    @user = current_user
    if @user.update(user_params)
      @user.cal_rem = @user.calorie_allowance
      @user.save
      flash[:notice] = "You updated your account"
      redirect_to root_path
    else
      flash[:notice] = "Failed to update"
      redirect_to root_path
    end
  end

private
  def user_params
    params.require(:user).permit(:weight, :calorie_allowance)
  end
end

app/controllers/workouts_controller.rb
class WorkoutsController < ApplicationController
  def index
    @user = current_user
    @workouts = @user.workouts
  end

  def new
    @user = current_user
    @workout = Workout.new
    @exercises = Exercise.all
  end

  def create
    @user = current_user
    @workout = @user.workouts.new(workout_params)
    @workout.cal_burned = @workout.workout_calc
    if @workout.save
      @user.cal_rem = @user.cal_rem + @workout.cal_burned
      @user.save
      @total_cal_burned = Workout.total_cal_burned(@user.id)
      flash[:notice] = "Workout successfully added!"
      respond_to do |format|
        format.html { redirect_to root_path }
        format.js { render layout: false }
      end
    else
      render :new
    end
  end

private
  def workout_params
    params.require(:workout).permit(:user_id, :exercise_id, :minutes, :cal_burned)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HealthAndFitness</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <nav>
        <p class="navbar-text pull-right">
          <% if user_signed_in? %>
            Logged in as <strong><%= current_user.email %></strong>.
            <%= link_to "Home", root_path %> | 
            <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %> |
            <%= link_to "Meal Log", user_meals_path(current_user) %> |
            <%= link_to "Workout Log", user_workouts_path(current_user) %>
          <% else %>
            <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
            <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
          <% end %>
        </p>
      </nav>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
    </div>
  </body>
</html>

app/views/meals/create.js.erb
$('.last_meal').append('<p><%= @meal.cal_gained %> calories gained over <%= @meal.servings %> servings</p>');

$('#cal-gained').html('<%= @total_cal_gained %>');
$('#cal-remaining').html('<%= @user.cal_rem %>');
$('#pieChartDiv').html("<%= j render('pages/pieChart') %>");

app/views/meals/index.html.erb
<h1>Meals You've Logged</h1>

<% @meals.each do |meal| %>
  <p><%= meal.cal_gained %> with <%= meal.servings %> servings</p>
<% end %>

app/views/meals/new.html.erb
<%= form_for [@user, @meal] do |f| %>
  <%= f.label :servings %>
  <%= f.number_field :servings %>
  <%= f.select(:food_id, @foods.map { |value| [ value.name, value.id ] })%>
  <%= f.submit %>
<% end %>

<hr>

<h3>Try searching for these foods:</h3>
<% @foods.each do |food| %>
  <p><%= food.name %>, <%= food.cal_serving %> calories</p>
<% end %>

app/views/pages/_foods.html.erb
<% if @food_results %>
  <% @food_results.each do |food| %>
  <p>
    <%= food.name %>
  </p>
  <% end %>
<% end %>

<% if params[:search] %>

  <%= will_paginate @food_results %>
<% end %>

app/views/pages/_pieChart.html.erb
  <%= pie_chart current_user.meals.group(:servings).sum(:cal_gained) %>

app/views/pages/index.html.erb
<h1>Home</h1>

<% if @user && !@user.calorie_allowance && !@user.weight %>
  <h3>Enter your user details </h3>
  <%= form_for @user do |f| %>
  <%= f.label :weight %>
  <%= f.number_field :weight, :step => 0.1 %>
  <%= f.label :calorie_allowance %>
  <%= f.number_field :calorie_allowance %>
  <%= f.submit %>
  <% end %>
<% elsif @user && @user.calorie_allowance && @user.weight %>
  <h3>Your Weight: <%= @user.weight %></h3>
  <h3>Your Calorie Allowance: <span id="cal-remaining"><%= @user.cal_rem %></span> / <%= @user.calorie_allowance %></h3>
  <h3>Total Calories Gained: <span id="cal-gained"><%= @total_cal_gained %></span></h3>
  <h3>Total Calories Burned: <span id="cal-burned"><%= @total_cal_burned %></span></h3>

  <%= link_to "Log your Meal", new_user_meal_path(@user) %>
  <br>
  <%= link_to "Log your Workout", new_user_workout_path(@user) %>

  <%= form_tag root_path, :method => 'get', remote: true, id: 'food_search_form', :enforce_utf8 => false do %>
    <p>
      <%= text_field_tag :search, params[:search] %>
      <%= submit_tag "Search", :name => nil %>
    </p>
  <% end %>

  <div id="pieChartDiv">
    <%= pie_chart @user.meals.group(:servings).sum(:cal_gained) %>
  </div>


  <div id="food_s_results">
    <%= render 'foods' %>
  </div>

  <hr>
  <br><br>
  <p>Log a Meal, son</p>
  <%= form_for [@user, @meal], remote: true do |f| %>
    <%= f.label :servings %>
    <%= f.number_field :servings %>
    <%= f.select(:food_id, @foods.map { |value| [ value.name, value.id ] })%>
    <%= f.submit %>
  <% end %>

  <p>Log a Workout, bro</p>
  <%= form_for [@user, @workout], remote:true do |f| %>
    <%= f.label :minutes %>
    <%= f.number_field :minutes %>
    <%= f.select(:exercise_id, @exercises.map { |value| [ value.description, value.id ] })%>
    <%= f.submit %>
  <% end %>

<div class="last_workout"></div>
<div class="last_meal"></div>

<% else %>
  <h3>Please Log In</h3>
<% end %>

app/views/pages/index.js.erb
$("#food_s_results").html("<%= j render('foods') %>");

app/views/workouts/create.js.erb
$('.last_workout').append('<p><%= @workout.cal_burned %> calories burned over <%= @workout.minutes %> minutes</p>')

$('#cal-burned').html('<%= @total_cal_burned %>');
$('#cal-remaining').html('<%= @user.cal_rem %>');

app/views/workouts/index.html.erb
<h1>Workouts You've Logged</h1>

<% @workouts.each do |workout| %>
  <p><%= workout.cal_burned %> calories burned over <%= workout.minutes %> minutes</p>
<% end %>

app/views/workouts/new.html.erb
<%= form_for [@user, @workout] do |f| %>
  <%= f.label :minutes %>
  <%= f.number_field :minutes %>
  <%= f.select(:exercise_id, @exercises.map { |value| [ value.description, value.id ] })%>
  <%= f.submit %>
<% end %>

<hr>

<h3>Try searching for these exercises:</h3>
<% @exercises.each do |exercise| %>
  <p><%= exercise.description %>: <%= exercise.cal_min %> calories burned per minute</p>
<% end %>